// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lisvelccglxpdlimnsaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxpc3ZlbGNjZ2x4cGRsaW1uc2FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDIwNzUsImV4cCI6MjA2MTQxODA3NX0.zFriOE6iyO1qBwGsjdTkeBoJaoNGAPzUiSr-wx6G-OY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);